### ISSUE TITLE
plyvel fails to build on every system.

### ISSUE THREAD

**Issue by ManuelSchneid3r** [alecalve/python-bitcoin-blockchain-parser#107]
tried manjaro, macos, several docker containers. this project depends on plyvel 1.2.0. meanwhile there is 1.5.0. which works ootb. please update the dependencies. why do you require this exact version at all?

**Comment by Bopobopob** [comment]
I encountered the same problem and eventually gave up and installed it without its dependencies. I expect some problems in the future, but that's future me's problem.

**Comment by ManuelSchneid3r** [comment]
@Bopobopob i ended up using ubuntu:18.04 in docker. jfyi regards

**Comment by ManuelSchneid3r** [comment]
Just touched it again and realized it it 20.04

**Comment by alecalve** [comment]
Updating to pylevel 1.5.1 should work
