### ISSUE TITLE
How to interpret Output.adresses

### ISSUE THREAD

**Issue by ManuelSchneid3r** [alecalve/python-bitcoin-blockchain-parser#108]
What is the meaning of [Output.adresses](https://github.com/alecalve/python-bitcoin-blockchain-parser/blob/master/blockchain_parser/output.py#L54)? Why is this a list? Afaik ouputs can have a single address only. How can I know where spent bitcoins will end up?

**Comment by alecalve** [comment]
In most cases, an output will have a single address. It can have multiple if it’s a multisig (BIP 11) output.
