### ISSUE TITLE
Add support for getting ordered blocks

### ISSUE THREAD

**Issue by picrypto** [alecalve/python-bitcoin-blockchain-parser#13]
I have been using this library in one of my projects and it is working perfectly but I have ran into a really big roadblock: I need the blocks that your library returns to be ordered as my code requires this to work. Could you please implement this when you get a chance of even tell me how to implment it myself. Thanks so much for building this! :)

**Comment by epicsol-inc** [comment]
Hi can you please add a sample python snippet explaining how to read blocks in order. I am trying to read all blocks in order from all blk files (blk00000.dat, blk00001.dat, ....)

**Comment by alecalve** [comment]
By default, the get_unordered_blocks will return them in the order they are in the files (blk00000.dat, blk00001.dat, ....) _but_ the order in those files is not the order in the chain.

**Comment by epicsol-inc** [comment]
@alecalve Thanks for responding. Firstly, thanks for the great work and I think i wasn't able to explain well. I understand that the files are read in order but i wanted to have a sample code for @asutoshpalai work to read blocks in order.
