### ISSUE TITLE
How can i get list of all addresses and hash160, having positive balance ?

### ISSUE THREAD

**Issue by agoora** [alecalve/python-bitcoin-blockchain-parser#19]
Please let me know.

**Comment by LoudMurmur** [comment]
you take your address pubkey, you start from block 0 to the last one
read each transactions
sum the input and ouput in aaaaaall the transactions for this address, and you get its balance.

**Comment by alecalve** [comment]
See https://github.com/alecalve/python-bitcoin-blockchain-parser/issues/40
