### ISSUE TITLE
Should input.py have an address? 

### ISSUE THREAD

**Issue by samcarlos** [alecalve/python-bitcoin-blockchain-parser#21]
Hello,

I was wondering if the input should have an associated address. Is there a way to obtain this information with this package? 

Thanks,
Sam

**Comment by alecalve** [comment]
From just using the block data, you cannot get the address associated with the input. At the raw transaction level, an input is just a pointer to a previous transaction output. To get the associated address, you have to dereference that pointer, which is quite costly if you don't have a database of the unspent outputs.

**Comment by samcarlos** [comment]
Thanks for your quick response! 

Looking at a blockchain transaction such as this https://blockexplorer.com/tx/6f37c134ce41f688f0b4f2b18286228f28c2c537750c24ce253681893dcfd18e it looks like there should be an associated input and output address for each transaction readily available. 

I guess blockexplorer does more than just look up a particular transaction? 

Thanks again,
Sam

**Comment by alecalve** [comment]
Exactly, block explorers do the dereferencing before storing the transactions so that end users don't have to.

**Comment by samcarlos** [comment]
Ok. Thanks for clearing that up 👍
