### ISSUE TITLE
How can I get the address from which a transaction originates? 

### ISSUE THREAD

**Issue by mattdornfeld** [alecalve/python-bitcoin-blockchain-parser#22]

**Comment by gimlids** [comment]
I'd like to know the answer as well. It is possible, right?

**Comment by gimlids** [comment]
Ah, I think I'm on to something here. Looks like an input is a reference to an output in a previous transaction:
![image](https://user-images.githubusercontent.com/186277/35476053-9103e954-0377-11e8-8353-a0d31f556c9b.png)

**Comment by alecalve** [comment]
Exact, each input references a previous transaction output which itself may have an address attached (for example, transactions creating Bitcoin do not have any address attached).
