### ISSUE TITLE
Your library cannot read blocks in blk00977.dat

### ISSUE THREAD

**Issue by pgwzzz** [alecalve/python-bitcoin-blockchain-parser#23]
Your library fails to read all the blocks in blk00977.dat.

I think every blocks after that such as blk00978.dat, blk00979.dat, ...

Could you check? Please.

Thank you.

**Comment by pgwzzz** [comment]
More specifically.

From this block, failed.

https://blockchain.info/block-index/1619616/0000000000000000001c8018d9cb3b742ef25114f27563e3fc4a1902167f9893

**Comment by brannondorsey** [comment]
I too would like to use this library to parse the blockchain past the segwit change. Is there any intention to support this or any forks that have already?

**Comment by brannondorsey** [comment]
I've added support for this in the `segwit` branch of [my fork](https://github.com/brangerbriz/python-bitcoin-blockchain-parser/tree/segwit). It isn't currently storing the segmented witnesses but it is correctly parsing blocks.

**Comment by alecalve** [comment]
Nice work! If you could create a PR for it so that I can look into it that'd be great.

I'll spend some time next week end going over the pending PRs and issues and resolving what can be resolved.

**Comment by brannondorsey** [comment]
PR created here https://github.com/alecalve/python-bitcoin-blockchain-parser/pull/24 😹. Great to hear you are planning to review some code this weekend and hopefully merge some stuff. I've been using this lib for the past few weeks and it really is superb. Let me know if you need help with anything.
