### ISSUE TITLE
exporting data into a JSON or CSV file. 

### ISSUE THREAD

**Issue by gurpsz** [alecalve/python-bitcoin-blockchain-parser#27]
Hi,
I have been trying to export data extracted by these parser libraries, however I am receiving so many different errors.  Below is my code: 

import sys
import pandas as pd
from blockchain_parser.blockchain import Blockchain
from datetime import datetime

blockchain = Blockchain(sys.argv[1])
for block in blockchain.get_unordered_blocks():
    for transaction in block.transactions:
        for output in transaction.outputs:
            if block.header.timestamp > datetime(2008, 1, 1):
                
                df = (block.header.timestamp, output.value)
                df_export = df.groupby([df[block.header.timestamp], output.value]).sum().reset_index()
				df_export = df_export.rename(coloums={block.header.timestamp : 'Time of transaction', output.value : 'Amount in Satoshi'})
				df_export.to_json('C:/btcdata.json', orient='records')

In the code above, I was trying to export data into a JSON file but I received the following errors:

 File "jsontimestamp.py", line 15
    df_export = df_export.rename(coloums={block.header.timestamp : 'Time of transaction', output.value : 'Amount in Satoshi'})
                                                                                                                             ^
TabError: inconsistent use of tabs and spaces in indentation

I have checked the indentation and it doesn't seem to be a problem.  Can you please help??

Thanks
Gurps

**Comment by brannondorsey** [comment]
`jsontimestamp.py` is a file you created, right? If so, I can guarantee that the problem is in fact that with inconsistencies with tabs and spaces in your file, not this library itself.

**Comment by brannondorsey** [comment]
In fact, I can see the inconsistency right there ^. "untab" the two lines below your `df.grouppy(...)` call.
