### ISSUE TITLE
Cache LevelDB index parsing

### ISSUE THREAD

**Issue by brannondorsey** [alecalve/python-bitcoin-blockchain-parser#39]
`Blockchain.get_ordered_blocks(...)` relies on Bitcoin's LevelDB database in `~/.bitcoin/blocks/index` to produce ordered blocks. This is great, except [parsing this LevelDB index](https://github.com/alecalve/python-bitcoin-blockchain-parser/blob/master/blockchain_parser/blockchain.py#L153) can take a few minutes or longer depending on the user's hardware. When testing new code that relies on this function this can be a huge slowdown if you have to wait 10+ minutes each time you run your code.

@alecalve, how would you feel about adding optional params to `get_ordered_blocks()` to control saving/loading the parsed LevelDB indexes using pickle? I've got a version of this working locally and enabling it while I'm deving is a lifesaver. I wanted to bring it up here and discuss it before making a PR. Caching is always tricky business because if the user doesn't know that it's enabled/how it works it can lead to unexpected results and headache. 

I'm imaging an interface like this:

```python
def get_ordered_blocks(self, index, start=0, end=None, cache=None, cache_file='~/.ordered-blocks-index.pickle'):
#...
```

`cache` could take the following values:
- `None`: caching is disabled and not used. This is the default behavior.
- `"save/load"` (and `"load/save"`): Saves cache to `cache_file` if it doesn't already exists. Otherwise loads it.
- `delete`: Delete `cache_file`. 

Or, perhaps an even simpler interface is this:

```python
def get_ordered_blocks(self, index, start=0, end=None, cache=None):
#...
```

Where cache can take on the following values:

- `None`: Caching is disabled and not used.
- `"path/to/cache.pickle"`: The cache file to create if none exists or to load from if one does. It is then up to the user to manually delete this file to reload the index.

Of course, either of these solutions will require explicit documentation of this feature in the README to avoid some of the pitfalls that could come with not understanding how this caching system works. 

I'm happy to take on this issue if we deem it sufficiently useful.

**Comment by brannondorsey** [comment]
@alecalve, any thoughts on this?

**Comment by alecalve** [comment]
I like the second interface better, I'm not sure about Pickle, having never used it before. It has some security implications, but since we're not developing wallet software, it's fine.

**Comment by brannondorsey** [comment]
Ok, I'll make an effort to clean up my code a bit and go with the second interface and PR here sometime soon. I agree pickle isn't the most elegant interface, but it so nicely transforms to python objects with minimal parsing overhead. I can experiment with JSON as well.

**Comment by alecalve** [comment]
I think it depends how large the resulting blob index is, if loading it via JSON is quite slow, then Pickle it is.
