### ISSUE TITLE
Ascii values of hex characters

### ISSUE THREAD

**Issue by aquirin** [alecalve/python-bitcoin-blockchain-parser#4]
With some version of Python the following checks return always False, resulting in few addresses being decoded:

(in output.py)

```
if len(hex_data) == 65 and hex_data[0] == 4:
if len(hex_data) == 33 and hex_data[0] in [2, 3]:
```

I would suggest doing this:

```
if len(hex_data) == 65 and ord(hex_data[0]) == 4:
if len(hex_data) == 33 and ord(hex_data[0]) in [2, 3]:
```

**Comment by alecalve** [comment]
Oh, do you have a list of affected versions? I'd like to add tests for it.

**Comment by aquirin** [comment]
I tested it with Python 2.7. As this function exists in 2.6 and 3.5 too, I guess these versions are affected too...

**Comment by alecalve** [comment]
Thanks for the follow up, I will check on my end and either use your fix or come up with a better way to detect addresses altogether.

**Comment by aquirin** [comment]
Great, you are welcome

**Comment by llamasoft** [comment]
Somewhat related:

Python 2.7.10 throws a ValueError when attempting to `int(data[0])` in util.py's `decode_varint`. ([demo](https://ideone.com/WzfL8U))
Python 3.4 does the same. ([demo](https://ideone.com/Q0ePVo))

Changing the code to `ord(data[0])` fixes the issue.

**Comment by alecalve** [comment]
I've just released a new version that should fix this issue, please tell me if everything works on your side
