### ISSUE TITLE
setup.py fails 

### ISSUE THREAD

**Issue by delgadod** [alecalve/python-bitcoin-blockchain-parser#42]
Hello,

I am trying to install this library. After installing all listed dependencies I run setup.py, only to have it fail with this errror:

> zip_safe flag not set; analyzing archive contents...
blockchain_parser.tests.test_transaction: module references __file__
warning: no files found matching 'plyvel/*.pxi'
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
plyvel/_plyvel.cpp: In function ‘int __pyx_f_6plyvel_7_plyvel_parse_options(leveldb::Options*, bool, bool, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, int, PyObject*, PyObject*)’:
plyvel/_plyvel.cpp:3341:22: error: ‘struct leveldb::Options’ has no member named ‘max_file_size’
     __pyx_v_options->max_file_size = __pyx_t_4;
                      ^
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Before the error, output from setup.py is:
[setup_before_error.txt](https://github.com/alecalve/python-bitcoin-blockchain-parser/files/1869676/setup_before_error.txt)

**Comment by alexmnv** [comment]
Ran into same error (Debian 7.7 x64)

**Comment by alecalve** [comment]
What version of the leveldb dev libraries do you have installed?

plyvel requires leveldb development libraries for LevelDB >1.2.X
