### ISSUE TITLE
Run parser simultaneously with running bitcoin node

### ISSUE THREAD

**Issue by Belobobr** [alecalve/python-bitcoin-blockchain-parser#43]
I want to write bitcoin cash wallet for educational purpose. 

I need to know about wallet balance and statistics (like spends during month), but:
1) according to https://en.bitcoin.it/wiki/Bitcoin_Core_0.11_(ch_2):_Data_Storage  the block cache is guaranteed to be flushed once an hour.
2) according to https://github.com/google/leveldb/blob/master/doc/index.md database may only be opened by one process at a time.

It seems:
a) i can't get information about last transactions
b) i can't run parser simultaneously with running bitcoin node

How can i get information about last transactions?

**Comment by alecalve** [comment]
You should be able to run the parser with the node running (if not, please details your issue).

As for getting last transactions, I don't think this software is best suited. I'd recommend using something like [the ZMQ socket notifications](https://github.com/bitcoin/bitcoin/blob/master/doc/zmq.md) which will send you transactions and blocks as they arrive.
