### ISSUE TITLE
Orphan blocks

### ISSUE THREAD

**Issue by alecalve** [alecalve/python-bitcoin-blockchain-parser#60]
https://github.com/BitMEXResearch/forkmonitor/issues/1#issuecomment-441867942

**Comment by alecalve** [comment]
> Does your blockchain-parser.py program take into account all issues (Including orphan blocks)? This is only referring to the get_unordered_blocks (Since this is the only one I use.) Thanks, there is no other way to find out so I had to comment on a random post.

I think it does although I'm not sure.

See #38

**Comment by alecalve** [comment]
@nwlezien

**Comment by nwlezien** [comment]
that link is referencing the get_ordered() function, does it work with the get_unordered(), "work" meaning filter out orphan blocks @alecalve

**Comment by nwlezien** [comment]
can I use the get_ordered() with windows? it seems like to download leveldb-dev which is necessary, you need ubuntu or linux

**Comment by nwlezien** [comment]
@alecalve I am getting an error bitcoin.core.script.CScriptTruncatedPushDataError: PUSHDATA(1): truncated data, do you know a way around this? Or why it is an issue?
