### ISSUE TITLE
Is there a method to extract OP_RETURN data from blocks?

### ISSUE THREAD

**Issue by brunoaduarte** [alecalve/python-bitcoin-blockchain-parser#65]
Is there a method to extract OP_RETURN data from blocks?

**Comment by jeamick** [comment]
I think there is more info there : 
- https://bitcoin.stackexchange.com/questions/37158/op-return-using-python
- https://github.com/coinspark/python-OP_RETURN/blob/master/OP_RETURN.py

Hope this helps @brunoaduarte
