### ISSUE TITLE
get_ordered_blocks function is missing

### ISSUE THREAD

**Issue by andmanousakis** [alecalve/python-bitcoin-blockchain-parser#68]
**This is the error I get when I try to parse the btc ordered blocks:**

Traceback (most recent call last):
  File "path.to.file", line 7, in <module>
    for block in blockchain.get_ordered_blocks(sys.argv[0] + '/Volumes/BTC_Blockch/blocks/index', end=1):
AttributeError: 'Blockchain' object has no attribute 'get_ordered_blocks'

**Also, I had to change from:**

sys.argv[1]  to  sys.argv[0]

**because I was getting the following error:**

Traceback (most recent call last):
  File "path.to.file", line 5, in <module>
    blockchain = Blockchain(sys.argv[1])
IndexError: list index out of range

**Comment by fishlao** [comment]
I found there is no get_ordered_blocks method in blockchain.py

**Comment by kuiwang** [comment]
same question as @fishlao 
'Blockchain' object has no attribute 'get_ordered_blocks'

**Comment by kuiwang** [comment]
i know why, i've installed blockchain_parser via pip which does NOT contains get_ordered_blocks,
but the source code in github really contains get_ordered_blocks.

**Comment by PiPinoccio** [comment]
Same here - I cannot find the "get_ordered_blocks".
