### ISSUE TITLE
testnet

### ISSUE THREAD

**Issue by huangxingge** [alecalve/python-bitcoin-blockchain-parser#77]
it dose not support testnet And witness_v0_keyhash ,witness_v0_scripthash?

**Comment by Xing-Huang** [comment]
def is_p2wpkh(self):
        return self.script.script[0] == 0 and self.script.script[1] == 20

    def is_p2wsh(self):
        return self.script.script[0] == 0 and self.script.script[1] == 32
it could be ok

**Comment by aa1756349463** [comment]
老哥你好，你知道python-bitcoin-blockchain-parser还能够解析最近的块吗？我解析的时候出现了错误，在CSDN上面有人给我说这个不能解析最近的块了，好像是协议的原因，然后我今天上午试了一下发现的确出现了错误

**Comment by alecalve** [comment]
The most recent version (0.1.5) of the library now supports SegWit
