### ISSUE TITLE
when i use Blockchain.get_ordered_blocks，,there is an error:

### ISSUE THREAD

**Issue by aa1756349463** [alecalve/python-bitcoin-blockchain-parser#80]
when i use Blockchain.get_ordered_blocks，,there is an error:TypeError: get_ordered_blocks() missing 1 required positional argument: 'index'
there are my code :import os
from blockchain_parser import blockchain
for block in blockchain.Blockchain.get_ordered_blocks(os.path.expanduser('~/snap/bitcoin-core/common/.bitcoin/blocks/index'),end=1000):
    print("height=%d block=%s" % (block.height, block.hash))

,,,,,, I don't konw why

**Comment by Lvl4Sword** [comment]
Using that same code without changing the path gives me the same thing:
```py
import os
from blockchain_parser import blockchain
for block in blockchain.Blockchain.get_ordered_blocks(os.path.expanduser('~/snap/bitcoin-core/common/.bitcoin/blocks/index'),end=1000):
    print("height=%d block=%s" % (block.height, block.hash))
```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>  TypeError: get_ordered_blocks() missing 1 required positional argument: 'index'

Taking a cursory glance at the code, I believe this might be an issue with ``plyvel``. The current version is 1.2.0 ( at least according to https://pypi.org/project/plyvel/ ), and the version pinned in ``requirements.txt`` is 1.0.4

**Comment by aa1756349463** [comment]
maybe the get_ordered_blocks is not available，emmmmm.....Can I have your contact information?I'd like to ask you some academic questions.  Like email.emmmm....my email number is 1756349463@qq.com

**Comment by Lvl4Sword** [comment]
@aa1756349463 What do you mean by academic questions? I'm also not sure as to what that has to do with this issue.

@alecalve Any idea as to what's going on here? I haven't had the time to be able to look at this in-depth, but perhaps it's something basic I've passed when skimming.

**Comment by alecalve** [comment]
You need to initialize a `Blockchain` object first:


```python3
import os
from blockchain_parser.blockchain import Blockchain

blockchain = Blockchain(os.path.expanduser('~/snap/bitcoin-core/common/.bitcoin/blocks'))
for block in blockchain.get_ordered_blocks(os.path.expanduser('~/snap/bitcoin-core/common/.bitcoin/blocks/index'),end=1000):
    print("height=%d block=%s" % (block.height, block.hash))

```

**Comment by Lvl4Sword** [comment]
If that's the case, the README is wrong:
https://github.com/alecalve/python-bitcoin-blockchain-parser#ordered-blocks

**Comment by alecalve** [comment]
indeed, it's fixed now
