### ISSUE TITLE
Double definition of hash property in transactions.py

### ISSUE THREAD

**Issue by jeanmonet** [alecalve/python-bitcoin-blockchain-parser#81]
First of all thank you for this great library. Is it still being maintained?

I note in https://github.com/alecalve/python-bitcoin-blockchain-parser/blob/5069a1d9af42a5a2173430e6946c2ea92e7b1fde/blockchain_parser/transaction.py#L103
that the property `hash` is defined twice. Didn't check, but thought the first definition is the old one, which became since Segwit `txid`. So the first property `hash` on line 103 should probably be deleted?

**Comment by alecalve** [comment]
Good catch!
