### ISSUE TITLE
is_unknown() method in script.py missing is_p2wsh and is_p2wpkh checks

### ISSUE THREAD

**Issue by jeanmonet** [alecalve/python-bitcoin-blockchain-parser#86]
Hi,
I noticed that the following method (`is_unknown()` in `script.py`):

https://github.com/alecalve/python-bitcoin-blockchain-parser/blob/ee5b9e2e28a0c0848d8d46b1c80d90549933fb71/blockchain_parser/script.py#L138

is missing checks for is_p2wsh and is_p2wpkh. Running `some_script.type` would return `p2wsh` for example, but running same `some_script.is_unknown()` would return true.

**Comment by alecalve** [comment]
good catch!

https://github.com/alecalve/python-bitcoin-blockchain-parser/commit/7a9e15c236b10d2a6dff5e696801c0641af72628 fixes it and adds tests for that
