### ISSUE TITLE
The results of the analysis are compared with those in the https://btc.com The query results above are different

### ISSUE THREAD

**Issue by aa1756349463** [alecalve/python-bitcoin-blockchain-parser#87]
Can this project parse the most recent block? After I synchronize the blocks, I use Unordered Blocks to analyze. The result of tx.hash is different from the result searched by btc.com, or it can’t be found on btc.com, it shows " No data matching the query was found. Please change the keyword and try again"
this is my code:

`blk = get_blocks('/home/zhang/.bitcoin/blocks/blk02276.dat')
for a in blk:
    block = Block(a)
    for tx in block.transactions:
        for output in tx.outputs:
            print("tx=%s type=%s value=%s" % (tx.hash, output.type, output.value))`

**Comment by aa1756349463** [comment]
The code above is a bit messy

blk = get_blocks('/home/bit/.bitcoin/blocks/blk02276.dat')
for a in blk:
    block = Block(a)
    for tx in block.transactions:
        for output in tx.outputs:
            print("tx=%s type=%s value=%s" % (tx.hash, output.type, output.value))

**Comment by aa1756349463** [comment]
The code above is a bit messy

from blockchain_parser.blockchain import Blockchain,get_files,get_blocks
from blockchain_parser.block import Block

# Instantiate the Blockchain by giving the path to the directory
# containing the .blk files created by bitcoind
blk = get_blocks('/home/zhang/.bitcoin/blocks/blk02276.dat')
for a in blk:
    block = Block(a)
    for tx in block.transactions:
        for output in tx.outputs:
            print("tx=%s type=%s value=%s" % (tx.hash, output.type, output.value))

**Comment by aa1756349463** [comment]
from blockchain_parser.blockchain import Blockchain,get_files,get_blocks
from blockchain_parser.block import Block
blk = get_blocks('/home/zhang/.bitcoin/blocks/blk02276.dat')
for a in blk:
    block = Block(a)
    for tx in block.transactions:
        for output in tx.outputs:
            print("tx=%s type=%s value=%s" % (tx.hash, output.type, output.value))

**Comment by alecalve** [comment]
Which version of the library are you using? Older ones lacked support for SegWit which might cause such an issue

**Comment by aa1756349463** [comment]
thank u,I will try the latest version

**Comment by aa1756349463** [comment]
hi,Dear Sir, I’m sorry to bother you again, I tried to reinstall the library today, PKG-INFO shows Version: 0.1.5, and then I tried to run the example program under Unordered Blocks, but the output is still wrong . Especially when "outputno=n" and the value of n is greater than 1, the output "tx=.........." cannot be found on btc.com, and the website interface displays 404, such as: tx=eee77d421df62022f45466c39298289db4423ed03108c3c391fcb23af45b4f02 outputno =6 type=p2sh value=3636517. If n is 0 or 1, it can be found.this is my code:
blockchain = Blockchain(os.path.expanduser('/home/zhang/.bitcoin/blocks/blk02275.dat'))
for block in blockchain.get_unordered_blocks():
    for tx in block.transactions:
        for no, output in enumerate(tx.outputs):
            print("tx=%s outputno=%d type=%s value=%s" % (tx.hash, no, output.type, output.value))

**Comment by alecalve** [comment]
I parsed my node's `blk02275.dat` file and could not find a transaction with hash `eee77d421df62022f45466c39298289db4423ed03108c3c391fcb23af45b4f02`.

Could you share that file so that I can replicate the bug?

**Comment by aa1756349463** [comment]
Of course, how can I send you the file blk02275? I tried to upload it to GitHub my repositories. Its size exceeded 100m and compressed to 107m, so the upload was limited. I tried many methods and failed. I'm trying to upload it to repositories. If not, can I send it to you by email?

**Comment by alecalve** [comment]
We identified the issue, the transaction could not be found by hash, but could be by txid.

**Comment by aa1756349463** [comment]
ok,thank you very much

**Comment by cirosantilli** [comment]
Thanks for finding this out, I was hit by the same issue until I found this post.

It would be good to convert the example in the README to use tx.txid rather than tx.hash, since txid is much more common/useful in general.
