### ISSUE TITLE
Block.height always None

### ISSUE THREAD

**Issue by mokafolio** [alecalve/python-bitcoin-blockchain-parser#9]
Is the height currently not parsed? It's always None for me and looking at the source it does not appear to be set anywhere, am I missing anything?

Thanks

**Comment by alecalve** [comment]
It's normal if you're using `get_unordered_blocks` since setting the height would require to parse the blockchain in the correct order (which is not implemented yet)

**Comment by mokafolio** [comment]
That makes perfect sense. For a project I am currently working on, I need the ordered blocks. As that is not implemented, yet, can't I just sort the blocks I parsed by the timestamp? Or would I have to manually start with one block and go find the one with the same previous hash?

**Comment by itoonx** [comment]
outputs address is the same sir

**Comment by alecalve** [comment]
This is now fixed by #28
